# Generated by Django 2.2.8 on 2020-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200206_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('figure', 'Фигурка'), ('earring', 'Серьги'), ('necklace', 'Кулон')], default='figure', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('awaiting', 'Ждет ответа'), ('confirmed', 'Подтвержден'), ('done', 'Выполнен')], max_length=10, null=True),
        ),
    ]
