# Generated by Django 2.2.8 on 2020-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200206_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('figure', 'Фигурка'), ('earring', 'Серьги'), ('necklace', 'Кулон')], max_length=10),
        ),
    ]
