# Generated by Django 2.2.8 on 2020-02-06 18:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200206_1805'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('cart', django.db.models.manager.Manager()),
            ],
        ),
    ]
