# Generated by Django 2.2.8 on 2020-02-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200207_0436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
