# Generated by Django 2.2.8 on 2020-02-07 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('customer', models.ForeignKey(on_delete='CASCADE', related_name='basket', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete='CASCADE', related_name='+', to='shop.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
