# Generated by Django 2.2.8 on 2020-02-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('awaiting', 'В обработке'), ('confirmed', 'Подтвержден'), ('done', 'Готов')], default='awaiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('badge', 'Значок'), ('earring', 'Серьги'), ('necklace', 'Кулон')], max_length=10),
        ),
    ]
