# Generated by Django 2.2.8 on 2020-02-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200208_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='product_images')),
                ('image2', models.ImageField(blank=True, upload_to='product_images')),
                ('image3', models.ImageField(blank=True, upload_to='product_images')),
                ('description', models.TextField()),
                ('size', models.PositiveIntegerField()),
            ],
        ),
    ]
