# Generated by Django 2.2.8 on 2020-02-08 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0017_custompurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompurchase',
            name='customer',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
