# Generated by Django 2.2.8 on 2020-02-08 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_custompurchase_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=2, null=True)),
                ('customer', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete='CASCADE', related_name='+', to='shop.Product')),
            ],
        ),
    ]
