# Generated by Django 2.2.8 on 2020-02-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200208_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/product_images'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
