# Generated by Django 2.2.8 on 2020-02-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200210_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompurchase',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='custompurchase',
            name='image1',
            field=models.ImageField(upload_to='static/images', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='custompurchase',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='custompurchase',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='custompurchase',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Размер'),
        ),
    ]
