# Generated by Django 2.2.8 on 2020-02-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200210_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompurchase',
            name='status',
            field=models.CharField(choices=[('awaiting', 'В обработке'), ('confirmed', 'Подтвержден'), ('done', 'Готов')], default='awaiting', max_length=10),
        ),
    ]
