# Generated by Django 2.2.8 on 2020-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompurchase',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение 1'),
        ),
    ]
