# Generated by Django 2.2.8 on 2020-02-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200218_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompurchase',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='custompurchase',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='custompurchase',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 3'),
        ),
    ]
