# Generated by Django 2.2.8 on 2020-02-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200218_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
    ]
